# Form implementation generated from reading ui file 'create_user_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_create_user_form(object):
    def __init__(self):
        super().__init__()

    def setupUi(self, create_user_form):
        create_user_form.setObjectName("create_user_form")
        QtCore.QDir.addSearchPath('icons', './views/icons')
        create_user_form.resize(659, 250)
        create_user_form.setMinimumSize(QtCore.QSize(650, 250))
        create_user_form.setStyleSheet("background-color: rgb(226,226,226) ;color: rgb(0,0,0)")
        self.gridLayout_2 = QtWidgets.QGridLayout(create_user_form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 10, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.last_name_label = QtWidgets.QLabel(parent=create_user_form)
        self.last_name_label.setMinimumSize(QtCore.QSize(100, 0))
        self.last_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.last_name_label.setObjectName("last_name_label")
        self.gridLayout.addWidget(self.last_name_label, 2, 0, 1, 1)
        self.first_name_label = QtWidgets.QLabel(parent=create_user_form)
        self.first_name_label.setMinimumSize(QtCore.QSize(120, 0))
        self.first_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.first_name_label.setObjectName("first_name_label")
        self.gridLayout.addWidget(self.first_name_label, 1, 0, 1, 1)
        self.close_btn = QtWidgets.QPushButton(parent=create_user_form)
        self.close_btn.setMinimumSize(QtCore.QSize(24, 24))
        self.close_btn.setMaximumSize(QtCore.QSize(24, 24))
        self.close_btn.setMouseTracking(False)
        self.close_btn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.close_btn.setStyleSheet("border: 0;")
        self.close_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:exit_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close_btn.setIcon(icon)
        self.close_btn.setIconSize(QtCore.QSize(24, 24))
        self.close_btn.setDefault(False)
        self.close_btn.setObjectName("close_btn")
        self.gridLayout.addWidget(self.close_btn, 0, 3, 1, 1)
        self.first_name_input = QtWidgets.QLineEdit(parent=create_user_form)
        self.first_name_input.setMinimumSize(QtCore.QSize(400, 40))
        self.first_name_input.setStyleSheet("background-color: rgb(255,255,255) ;color: rgb(0,0,0)")
        self.first_name_input.setObjectName("first_name_input")
        self.gridLayout.addWidget(self.first_name_input, 1, 1, 1, 2)
        self.last_name_input = QtWidgets.QLineEdit(parent=create_user_form)
        self.last_name_input.setMinimumSize(QtCore.QSize(400, 40))
        self.last_name_input.setStyleSheet("background-color: rgb(255,255,255) ;\n"
"color: rgb(0,0,0);")
        self.last_name_input.setObjectName("last_name_input")
        self.gridLayout.addWidget(self.last_name_input, 2, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(360, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.add_user_btn = QtWidgets.QPushButton(parent=create_user_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_user_btn.sizePolicy().hasHeightForWidth())
        self.add_user_btn.setSizePolicy(sizePolicy)
        self.add_user_btn.setMaximumSize(QtCore.QSize(200, 25))
        self.add_user_btn.setBaseSize(QtCore.QSize(0, 0))
        self.add_user_btn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.add_user_btn.setStyleSheet("background-color: rgb(255,255,255) ;\n"
"color: rgb(0,0,0);\n"
"padding: 6px;")
        self.add_user_btn.setCheckable(False)
        self.add_user_btn.setChecked(False)
        self.add_user_btn.setAutoDefault(False)
        self.add_user_btn.setDefault(False)
        self.add_user_btn.setFlat(False)
        self.add_user_btn.setObjectName("add_user_btn")
        self.gridLayout.addWidget(self.add_user_btn, 4, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(create_user_form)
        QtCore.QMetaObject.connectSlotsByName(create_user_form)

    def retranslateUi(self, create_user_form):
        _translate = QtCore.QCoreApplication.translate
        create_user_form.setWindowTitle(_translate("create_user_form", "Form"))
        self.last_name_label.setText(_translate("create_user_form", "LAST NAME"))
        self.first_name_label.setText(_translate("create_user_form", "FIRST NAME"))
        self.add_user_btn.setText(_translate("create_user_form", "CREATE A USER"))
