# Form implementation generated from reading ui file 'create_user_form.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_create_user_form(object):
    def __init__(self):
        super().__init__()

    def setupUi(self, create_user_form):
        QtCore.QDir.addSearchPath('icons', './views/icons')
        create_user_form.setObjectName("create_user_form")
        create_user_form.resize(720, 515)
        create_user_form.setMinimumSize(QtCore.QSize(720, 515))
        self.gridLayout_2 = QtWidgets.QGridLayout(create_user_form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.id_label = QtWidgets.QLabel(parent=create_user_form)
        self.id_label.setMinimumSize(QtCore.QSize(176, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.id_label.setFont(font)
        self.id_label.setObjectName("id_label")
        self.gridLayout.addWidget(self.id_label, 1, 0, 1, 1)
        self.age_label = QtWidgets.QLabel(parent=create_user_form)
        self.age_label.setMinimumSize(QtCore.QSize(176, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.age_label.setFont(font)
        self.age_label.setObjectName("age_label")
        self.gridLayout.addWidget(self.age_label, 4, 0, 1, 1)
        self.id_input = QtWidgets.QLineEdit(parent=create_user_form)
        self.id_input.setMinimumSize(QtCore.QSize(400, 40))
        self.id_input.setObjectName("id_input")
        self.gridLayout.addWidget(self.id_input, 1, 1, 1, 2)
        self.add_user_btn = QtWidgets.QPushButton(parent=create_user_form)
        self.add_user_btn.setMaximumSize(QtCore.QSize(156, 23))
        self.add_user_btn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.add_user_btn.setObjectName("add_user_btn")
        self.gridLayout.addWidget(self.add_user_btn, 5, 2, 1, 1)
        self.first_name_label = QtWidgets.QLabel(parent=create_user_form)
        self.first_name_label.setMinimumSize(QtCore.QSize(176, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.first_name_label.setFont(font)
        self.first_name_label.setObjectName("first_name_label")
        self.gridLayout.addWidget(self.first_name_label, 2, 0, 1, 1)
        self.last_name_label = QtWidgets.QLabel(parent=create_user_form)
        self.last_name_label.setMinimumSize(QtCore.QSize(176, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.last_name_label.setFont(font)
        self.last_name_label.setObjectName("last_name_label")
        self.gridLayout.addWidget(self.last_name_label, 3, 0, 1, 1)
        self.first_name_input = QtWidgets.QLineEdit(parent=create_user_form)
        self.first_name_input.setMinimumSize(QtCore.QSize(400, 40))
        self.first_name_input.setObjectName("first_name_input")
        self.gridLayout.addWidget(self.first_name_input, 2, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(384, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        self.last_name_input = QtWidgets.QLineEdit(parent=create_user_form)
        self.last_name_input.setMinimumSize(QtCore.QSize(400, 40))
        self.last_name_input.setObjectName("last_name_input")
        self.gridLayout.addWidget(self.last_name_input, 3, 1, 1, 2)
        self.age_input = QtWidgets.QLineEdit(parent=create_user_form)
        self.age_input.setMinimumSize(QtCore.QSize(400, 40))
        self.age_input.setObjectName("age_input")
        self.gridLayout.addWidget(self.age_input, 4, 1, 1, 2)
        self.close_btn = QtWidgets.QPushButton(parent=create_user_form)
        self.close_btn.setMinimumSize(QtCore.QSize(24, 24))
        self.close_btn.setMaximumSize(QtCore.QSize(24, 24))
        self.close_btn.setStyleSheet("border: 0;")
        self.close_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:exit_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close_btn.setIcon(icon)
        self.close_btn.setIconSize(QtCore.QSize(24, 24))
        self.close_btn.setObjectName("close_btn")
        self.gridLayout.addWidget(self.close_btn, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(create_user_form)
        QtCore.QMetaObject.connectSlotsByName(create_user_form)

    def retranslateUi(self, create_user_form):
        _translate = QtCore.QCoreApplication.translate
        create_user_form.setWindowTitle(_translate("create_user_form", "Form"))
        self.id_label.setText(_translate("create_user_form", "PATIENT ID"))
        self.age_label.setText(_translate("create_user_form", "AGE"))
        self.add_user_btn.setText(_translate("create_user_form", "CREATE A USER"))
        self.first_name_label.setText(_translate("create_user_form", "FIRST NAME"))
        self.last_name_label.setText(_translate("create_user_form", "LAST NAME"))

