# Form implementation generated from reading ui file 'delete_session_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_delete_session_form(object):
    def __init__(self):
        super().__init__()
    def setupUi(self, delete_session_form):
        delete_session_form.setObjectName("delete_session_form")
        delete_session_form.resize(428, 136)
        delete_session_form.setStyleSheet("background-color: rgb(226,226,226) ;color: rgb(0,0,0)")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=delete_session_form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.delete_session_button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.delete_session_button.setStyleSheet("background-color: rgb(255,255,255) ;color: rgb(0,0,0)")
        self.delete_session_button.setObjectName("delete_session_button")
        self.gridLayout.addWidget(self.delete_session_button, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.close_btn = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.close_btn.setMinimumSize(QtCore.QSize(24, 24))
        self.close_btn.setMaximumSize(QtCore.QSize(24, 24))
        self.close_btn.setMouseTracking(False)
        self.close_btn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.close_btn.setStyleSheet("border: 0;")
        self.close_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:exit_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close_btn.setIcon(icon)
        self.close_btn.setIconSize(QtCore.QSize(24, 24))
        self.close_btn.setDefault(False)
        self.close_btn.setObjectName("close_btn")
        self.gridLayout.addWidget(self.close_btn, 0, 2, 1, 1)

        self.retranslateUi(delete_session_form)
        QtCore.QMetaObject.connectSlotsByName(delete_session_form)

    def retranslateUi(self, delete_session_form):
        _translate = QtCore.QCoreApplication.translate
        delete_session_form.setWindowTitle(_translate("delete_session_form", "Form"))
        self.label.setText(_translate("delete_session_form", "Are you sure you want to delete the session?"))
        self.delete_session_button.setText(_translate("delete_session_form", "DELETE THE SESSION"))

