# Form implementation generated from reading ui file 'first_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self):
        super().__init__()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(908, 586)
        QtCore.QDir.addSearchPath('icons', './views/icons')
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.add_user_btn = QtWidgets.QPushButton(parent=Form)
        self.add_user_btn.setStyleSheet("border:0;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:plus_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_user_btn.setIcon(icon)
        self.add_user_btn.setIconSize(QtCore.QSize(50, 50))
        self.add_user_btn.setObjectName("add_user_btn")
        self.gridLayout.addWidget(self.add_user_btn, 1, 3, 1, 1)
        self.user_list = QtWidgets.QComboBox(parent=Form)
        self.user_list.setMinimumSize(QtCore.QSize(484, 79))
        self.user_list.setEditable(True)
        self.user_list.setObjectName("user_list")
        self.gridLayout.addWidget(self.user_list, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 5, 1)
        self.add_session_btn = QtWidgets.QPushButton(parent=Form)
        self.add_session_btn.setStyleSheet("border:0;")
        self.add_session_btn.setIcon(icon)
        self.add_session_btn.setIconSize(QtCore.QSize(50, 50))
        self.add_session_btn.setObjectName("add_session_btn")
        self.gridLayout.addWidget(self.add_session_btn, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 5, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 3)
        self.user_icon = QtWidgets.QLabel(parent=Form)
        self.user_icon.setPixmap(QtGui.QPixmap("icons:user_icon.png"))
        self.user_icon.setScaledContents(False)
        self.user_icon.setObjectName("user_icon")
        self.gridLayout.addWidget(self.user_icon, 1, 1, 1, 1)
        self.session_icon = QtWidgets.QLabel(parent=Form)
        self.session_icon.setPixmap(QtGui.QPixmap("icons:pen_icon.png"))
        self.session_icon.setObjectName("session_icon")
        self.gridLayout.addWidget(self.session_icon, 2, 1, 1, 1)
        self.session_list = QtWidgets.QComboBox(parent=Form)
        self.session_list.setMinimumSize(QtCore.QSize(484, 79))
        self.session_list.setEditable(True)
        self.session_list.setObjectName("session_list")
        self.gridLayout.addWidget(self.session_list, 2, 2, 1, 1)
        self.go_to_main = QtWidgets.QPushButton(parent=Form)
        self.go_to_main.setObjectName("go_to_main")
        self.gridLayout.addWidget(self.go_to_main, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.user_list.setCurrentText(_translate("Form", "SELECT A USER"))
        self.session_list.setCurrentText(_translate("Form", "SELECT A SESSION"))
        self.go_to_main.setText(_translate("Form", "START THE SESSION"))


