# Form implementation generated from reading ui file 'start_session_widget.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_session_create(object):
    def __init__(self):
        super().__init__()

    def setupUi(self, session_create):
        QtCore.QDir.addSearchPath('icons', './widgets/icons')
        session_create.setObjectName("session_create")
        session_create.resize(561, 183)
        self.gridLayout_4 = QtWidgets.QGridLayout(session_create)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(293, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.session_nr_label = QtWidgets.QLabel(parent=session_create)
        self.session_nr_label.setMinimumSize(QtCore.QSize(176, 0))
        self.session_nr_label.setMaximumSize(QtCore.QSize(176, 23))
        self.session_nr_label.setObjectName("session_nr_label")
        self.gridLayout_3.addWidget(self.session_nr_label, 1, 0, 1, 1)
        self.close_btn = QtWidgets.QPushButton(parent=session_create)
        self.close_btn.setMinimumSize(QtCore.QSize(24, 24))
        self.close_btn.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.close_btn.setStyleSheet("border:0;")
        self.close_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:exit_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close_btn.setIcon(icon)
        self.close_btn.setIconSize(QtCore.QSize(24, 24))
        self.close_btn.setObjectName("close_btn")
        self.gridLayout_3.addWidget(self.close_btn, 0, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.start_session_btn = QtWidgets.QPushButton(parent=session_create)
        self.start_session_btn.setMinimumSize(QtCore.QSize(249, 40))
        self.start_session_btn.setObjectName("start_session_btn")
        self.gridLayout.addWidget(self.start_session_btn, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 2, 0, 1, 2)
        self.session_nr_input = QtWidgets.QLineEdit(parent=session_create)
        self.session_nr_input.setMinimumSize(QtCore.QSize(293, 40))
        self.session_nr_input.setText("")
        self.session_nr_input.setObjectName("session_nr_input")
        self.gridLayout_3.addWidget(self.session_nr_input, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(session_create)
        QtCore.QMetaObject.connectSlotsByName(session_create)

    def retranslateUi(self, session_create):
        _translate = QtCore.QCoreApplication.translate
        session_create.setWindowTitle(_translate("session_create", "Form"))
        self.session_nr_label.setText(_translate("session_create", "SESSION NUMBER"))
        self.start_session_btn.setText(_translate("session_create", "PushButton"))

